# Generated by Django 3.2.4 on 2021-06-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imagen',
            field=models.ImageField(default='', upload_to='products/'),
            preserve_default=False,
        ),
    ]
